### PR TITLE
Many fixes related to pr_dump and support of long Uident in `let open ... in`.

### PR DESCRIPTION
**Pull request by Kakadu**
My patches from the email. I decided not to split them into separate pull requests yet.

### CODE REVIEW

**Comment by roglo** [comment]
A good thing would be examples showing the problems (one example for each problem), including complete ml and/or mli file(s), the process of compilation, and the displayed errors or warnings. It would allow me to see the problems, look at where I think they should be fixed and see if your solutions are good or not. Thank you.

**Comment by Kakadu** [comment]
Are you talking about examples in commit messages or somewhere in the
source tree. In the latter case where can I read how to integrate them
properly?

**Comment by Kakadu** [comment]
About recursive modules.

````
➜  camlp5-work git:(1131939) ✗ ocamlfind ocamlc -dparsetree recmod.ml 
[
  structure_item (recmod.ml[1,0+0]..[1,0+35])
    Pstr_recmodule
    [
      "A" (recmod.ml[1,0+11]..[1,0+12])
        module_expr (recmod.ml[1,0+13]..[1,0+35])
          Pmod_constraint
          module_expr (recmod.ml[1,0+25]..[1,0+35])
            Pmod_structure
            []
          module_type (recmod.ml[1,0+15]..[1,0+22])
            Pmty_signature
            []
    ]
]

➜  camlp5-work git:(1131939) ✗ ocamlfind ocamlc -dparsetree recmod.ml -pp etc/camlp5o
[
  structure_item (recmod.ml[1,0+0]..[1,0+35])
    Pstr_recmodule
    [
      "A" (_none_[1,0+-1]..[1,0+-1]) ghost
        module_expr (recmod.ml[1,0+25]..[1,0+35])
          Pmod_structure
          []
    ]
]

File "recmod.ml", line 1, characters 25-35:
Error: Recursive modules require an explicit module type.
➜  camlp5-work git:(1131939) ✗ cat recmod.ml
module rec A : sig end = struct end
````

**Comment by Kakadu** [comment]
An example for virtual vals can be tricky. We kind of have syntax extension which constructs `CgVir` nodes in the parse tree which are expected to represent something virtual but I don't know exactly what. It is not possible to construct them without a syntax extension.  These node are dumped as virtual methods when we use `pr_o.cmo` and as virtual vals with `pr_dump`.  I fixed pr_dump implementation for consistency. I'm not sure why we even need this kind of nodes in camlp5 syntax tree......

**Comment by roglo** [comment]
If you could put the source files having errors in the logs, the shortest possible and, at least, being fully compilable, that would be cool.

**Comment by Kakadu** [comment]
@roglo I don entirely follow your last comment. What do you means saying `logs`: ICHANGES file in the root of the repo or commit messages? How should I improve that commit message? https://github.com/camlp5/camlp5/pull/1/commits/ada0249327c6a37f8212403bb3571840c6800bcf

**Comment by nojb** [comment]
I think he means that you should include the contents of the file you used `recmod.ml` in its entirety in the commit message so that he can reproduce the issue himself.

**Comment by Kakadu** [comment]
@nojb But it is already there!

**Comment by nojb** [comment]
Ah, yes, my apologies -- I had not seen that the file was included at the end!

**Comment by roglo** [comment]
Sorry I did not see them either at my first glance: they are so short! I can look a them now, and I tell you.

**Comment by roglo** [comment]
Done.

**Comment by Kakadu** [comment]
@roglo What about https://github.com/camlp5/camlp5/pull/1/commits/be346c207e813684eb6a0a7ad26d6d91d749be70 ?

**Comment by roglo** [comment]
Sorry. Forgot it. Ok, I look at it.

**Comment by roglo** [comment]
Ok, done.

**Pull request closed without merging**
