### PR TITLE
Fix OCaml/Scheme comparison table in the docs

### PR DESCRIPTION
**Pull request by drjdn**
Minor fix to the docs.

### CODE REVIEW

**Comment by chetmurthy** [comment]
Do you use the Scheme syntax extension?  I ask b/c if you do, then ..... you'd be the first one I've heard of, and I would be *happy* to learn of *any* problems you have, which I would love to get a-fixin' !

**Comment by drjdn** [comment]
Github isn't working for me currently.  But yes, I started a project some
time ago that I've come back to.   Was planning to post shortly with a link
to the appropriate docs.

**Comment by chetmurthy** [comment]
Thank you!

**Comment by chetmurthy** [comment]
If you have complaints or wishes about the Scheme extension (or, really, anything about Camlp5), I'd be happy to hear them.  For the Scheme extension, I would like to hew as closely to Scheme as possible, but I recognize that that might not be possible.  For Camlp5, I'm always happy to fix bugs and consider any requests for improvements.

**Comment by drjdn** [comment]
That project I was taking about is now up on my github account ([p5scm](https://github.com/drjdn/p5scm)).  All of the `camlp5` specific stuff is in the `src/camlp5` directory.  I did most of this a while ago but the very little that was done there was to hook things up with `utop`.  I'm sure there is a much better way of doing this but I wasn't trying to be fancy just trying to get it to work.  The motivation behind this was a discussion about `ppxlib` and a standardized AST.

**Pull request merged**
